services:
  devcontainer:
    image: novigoconsulting/visualstudiocodedevcontainer
    platform: linux/amd64
    container_name: devcontainer
    volumes:
      - /workspaces:/home/vscode:cached
    command: sleep infinity
    network_mode: service:nginx
    depends_on:
      - nginx
      - db
      

  # PHP-FPM 7.3
  php73:
    image: novigoconsulting/php73
    platform: linux/amd64
    container_name: php-fpm-73
    volumes:
      - ${WORKSPACE_FOLDER:-/workspaces}:/var/www/html
      - ./conf/php73/php.ini:/etc/php/7.3/fpm/conf.d/php.ini
    networks:
      - app_network

  # PHP-FPM 7.4
  php74:
    image: novigoconsulting/php74
    platform: linux/amd64
    container_name: php-fpm-74
    volumes:
      - ${WORKSPACE_FOLDER:-/workspaces}:/var/www/html
      - ./conf/php74/php.ini:/etc/php/7.4/fpm/conf.d/php.ini
    networks:
      - app_network

# PHP-FPM 8.0
  php80:
    image: novigoconsulting/php80
    platform: linux/amd64
    container_name: php-fpm-80
    restart: always
    volumes:
      - ${WORKSPACE_FOLDER:-/workspaces}:/var/www/html
      - ./conf/php80/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - app_network

  # PHP-FPM 8.2
  php82:
    image: novigoconsulting/php82
    platform: linux/amd64
    container_name: php-fpm-82
    restart: always
    volumes:
      - ${WORKSPACE_FOLDER:-/workspaces}:/var/www/html
      - ./conf/php82/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - app_network

  # PHP-FPM 8.4
  php84:
    image: novigoconsulting/php84
    platform: linux/amd64
    container_name: php-fpm-84
    restart: always
    volumes:
      - ${WORKSPACE_FOLDER:-/workspaces}:/var/www/html
      - ./conf/php84/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - app_network
  
  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    expose:
       - "8073"
       - "8074"
       - "8080"
       - "8082"
       - "8084"
       - "3306"
    volumes:
      - ${WORKSPACE_FOLDER:-/workspaces}:/var/www/html
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8073:8073"
      - "8074:8074"
      - "8080:8080"
      - "8082:8082"
      - "8084:8084"
    depends_on:
      - php73
      - php74
      - php80
      - php82
      - php84
    networks:
      - app_network

  # MariaDB Database
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-Novigo2025!!}
      MYSQL_DATABASE: ${DB_NAME:-my_database}
      MYSQL_USER: ${DB_USER:-db_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-Novigo2025!!}
    volumes:
      - mariadb_data:/var/lib/mysql
    network_mode: service:nginx

  # PHPMyAdmin
  # phpmyadmin:
   #  image: phpmyadmin/phpmyadmin
    # container_name: phpmyadmin
    # restart: always
    # environment:
     #  PMA_HOST: db
      # PMA_PORT: 3306
      # MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-Novigo2025!!}
      # Increase file upload limits to 512MB
     #  UPLOAD_LIMIT: 512M
      # MEMORY_LIMIT: 512M
      # MAX_EXECUTION_TIME: 300
    # depends_on:
     #  - db
   #  network_mode: service:nginx

volumes:
  mariadb_data:
    driver: local

networks:
  app_network:
    driver: bridge

